### PR TITLE
update to 0.2.1

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I left the build number at 1000, not sure if that's still the correct thing to do when things are still going to the gcc7 channel.

### CODE REVIEW

**Comment by dpryan79** [comment]
I've reset the build number to 0, please someone let me know if it should stay in the thousands.

**Comment by bgruening** [comment]
I think this is ok.

**Comment by dpryan79** [comment]
As long as it's not going to cause an issue with labels (granted, there's only a few more hours where that's an issue) then the other PR can be closed. I got a different answer on gitter, but only after I merged it here.

**Comment by bgruening** [comment]
It's an noarch package, so this does not really matter imho.

**Comment by dpryan79** [comment]
@bgruening Can you fix the label here real quick then? https://anaconda.org/conda-forge/r-tidytree/files

**Comment by bgruening** [comment]
Done.

**Pull request merged**
